version: '3.8'

services:
  db:
    image: mariadb:11.5
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: mercado
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
    ports:
      - "3306:3306" 
    volumes:
      - db_data:/var/lib/mysql

  php:
    build:
      context: .
    restart: unless-stopped
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      -  ./src/config/php.ini:/usr/local/etc/php/php.ini

volumes:
  db_data:
      driver: local