@startuml Categoria

class Conexao {
    +__construct(): void:  "Inicia a conexão com o banco de dados utilizando configurações específicas."
}

package "Categoria" {
    class Categoria {
        -Conexao conexao
        +__construct() : void : "Inicializa a instância da classe."
        +excluir(int id) : void : "Exclui uma categoria do banco de dados."
        +listarTudo() : array : "Retorna todas as categorias ativas."
    }

    Categoria --> Conexao: usa
}
@enduml