@startuml Validação

package "Validação" {
    class Validacao {
        +obterDadosPost(array filtros) : array : "Valida e recupera os dados do POST com base nos filtros fornecidos."
    }

    exception ValidacaoException extends Exception {
        +__construct() : void : "Constrói uma nova ValidacaoException."
    }
    
    Validacao --> ValidacaoException : lança

}
@enduml